#!/bin/bash

# List of programming languages and their extensions
declare -A languages=(
    ["Assembly"]=".a"
    ["ABAP"]=".abap"
    ["Ada"]=".ada"
    ["APL"]=".apl"
    ["Assembly Language"]=".asm"
    ["AWK"]=".awk"
    ["ActionScript"]=".actionscript"
    ["Agda"]=".agda"
    ["B"]=".b"
    ["Bash"]=".bash"
    ["Bourne shell script"]=".bc"
    ["Bazel"]=".bzl"
    ["C"]=".c"
    ["C++"]=".cpp"
    ["C#"]=".cs"
    ["COBOL"]=".cob"
    ["Clojure"]=".clj"
    ["CoffeeScript"]=".coffee"
    ["D"]=".d"
    ["Dart"]=".dart"
    ["Emacs Lisp"]=".el"
    ["Erlang"]=".erl"
    ["Fortran"]=".f"
    ["F#"]=".fs"
    ["Go"]=".go"
    ["Groovy"]=".groovy"
    ["C Header"]=".h"
    ["Haskell"]=".hs"
    ["Java"]=".java"
    ["JavaScript"]=".js"
    ["Julia"]=".jl"
    ["K"]=".k"
    ["Kotlin"]=".kt"
    ["Lex"]=".l"
    ["Lua"]=".lua"
    ["Lisp"]=".lisp"
    ["MATLAB"]=".m"
    ["ML"]=".ml"
    ["MQL"]=".mql"
    ["NCL"]=".ncl"
    ["Nim"]=".nim"
    ["Objective-C"]=".objc"
    ["Oz"]=".oz"
    ["Pascal"]=".pas"
    ["Perl"]=".perl"
    ["PHP"]=".php"
    ["Perl"]=".pl"
    ["Python"]=".py"
    ["R"]=".r"
    ["Ruby"]=".rb"
    ["Raku"]=".raku"
    ["Scala"]=".scala"
    ["Scheme"]=".scm"
    ["Shell Script"]=".sh"
    ["SQL"]=".sql"
    ["Swift"]=".swift"
    ["TypeScript"]=".ts"
    ["Tcl"]=".tcl"
    ["V"]=".v"
    ["Vala"]=".vala"
    ["WebAssembly Text Format"]=".wat"
    ["XML"]=".xml"
    ["XSLT"]=".xsl"
    ["Zig"]=".z"
    ["Rust"]=".rs"
)

# Create files for each language
for lang in "${!languages[@]}"; do
    ext=${languages[$lang]}
    touch "${lang}${ext}"
done

echo "Files created for each programming language."
